/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.padaria.padariaapp.telas;

import com.padaria.padariaapp.conexao.*;
import com.padaria.padariaapp.entidades.Endereco;
import com.padaria.padariaapp.entidades.FormaPagamento;
import com.padaria.padariaapp.entidades.Fornecedor;
import com.padaria.padariaapp.entidades.Funcionario;
import com.padaria.padariaapp.entidades.Produto;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author Enzo Teves
 */
public class Padaria extends javax.swing.JFrame {

    private DefaultListModel<Fornecedor> listaFornecedores = new DefaultListModel<>();
    private Fornecedor produtoFornecedorSelecionado = null;

    /**
     * Creates new form Padaria
     */
    public Padaria() {
        initComponents();
        listarFornecedores();
    }

    private void listarFornecedores() {
        listaFornecedores.clear();
        ArrayList<Fornecedor> fornecedores = new ListarFornecedores().listar();

        fornecedores.forEach(f -> {
            listaFornecedores.addElement(f);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabsPadaria = new javax.swing.JTabbedPane();
        painelCadastroFornecedor = new javax.swing.JPanel();
        tituloDadosFornecedor = new javax.swing.JLabel();
        codigoFornecedor = new javax.swing.JTextField();
        labelCodigoFornecedor = new javax.swing.JLabel();
        labelNomeFornecedor = new javax.swing.JLabel();
        nomeFornecedor = new javax.swing.JTextField();
        labelTelefoneFornecedor = new javax.swing.JLabel();
        telefoneFornecedor = new javax.swing.JTextField();
        labelEmailFornecedor = new javax.swing.JLabel();
        emailFornecedor = new javax.swing.JTextField();
        tituloEnderecoFornecedor = new javax.swing.JLabel();
        labelCodigoEndereco = new javax.swing.JLabel();
        codigoEndereco = new javax.swing.JTextField();
        labelCepEndereco = new javax.swing.JLabel();
        cepEndereco = new javax.swing.JTextField();
        labelCidadeEndereco = new javax.swing.JLabel();
        cidadeEndereco = new javax.swing.JTextField();
        labelEstadoEndereco = new javax.swing.JLabel();
        estadoEndereco = new javax.swing.JTextField();
        botaoSalvarCadastroFornecedor = new javax.swing.JButton();
        botaoCancelarCadastroFornecedor = new javax.swing.JButton();
        painelCadastroProduto = new javax.swing.JPanel();
        tituloDadosProduto = new javax.swing.JLabel();
        labelCodigoProduto = new javax.swing.JLabel();
        codigoProduto = new javax.swing.JTextField();
        labelDescricaoProduto = new javax.swing.JLabel();
        descricaoProduto = new javax.swing.JTextField();
        labelValorProduto = new javax.swing.JLabel();
        valorProduto = new javax.swing.JFormattedTextField();
        labelFornecedorProduto = new javax.swing.JLabel();
        botaoSalvarProduto = new javax.swing.JButton();
        botaoCancelarCadastroProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtoFornecedor = new javax.swing.JList<>();
        painelCadastroFuncionario = new javax.swing.JPanel();
        tituloDadosFuncionario = new javax.swing.JLabel();
        labelCodigoFuncionario = new javax.swing.JLabel();
        codigoFuncionario = new javax.swing.JTextField();
        labelNomeFuncionario = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        labelCpfFuncionario = new javax.swing.JLabel();
        cpfFuncionario = new javax.swing.JTextField();
        labelCargoFuncionario = new javax.swing.JLabel();
        cargoFuncionario = new javax.swing.JTextField();
        botaoCancelarFuncionario = new javax.swing.JButton();
        botaoSalvarFuncionario = new javax.swing.JButton();
        painelCadastroFormaPagamento = new javax.swing.JPanel();
        tituloFormaPagamento = new javax.swing.JLabel();
        labelCodigoFormaPagamento = new javax.swing.JLabel();
        codigoFormaPagamento = new javax.swing.JTextField();
        labelDescricaoFormaPagamento = new javax.swing.JLabel();
        descricaoFormaPagamento = new javax.swing.JTextField();
        botaoSalvarFormaPagamento = new javax.swing.JButton();
        botaoCancelarFormaPagamento = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuComanda = new javax.swing.JMenu();
        menuNovaComanda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabsPadaria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabsPadariaStateChanged(evt);
            }
        });

        tituloDadosFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloDadosFornecedor.setText("DADOS DO FORNECEDOR ");

        codigoFornecedor.setToolTipText("código do fornecedor");
        codigoFornecedor.setEnabled(false);

        labelCodigoFornecedor.setText("Código");

        labelNomeFornecedor.setText("Nome");

        labelTelefoneFornecedor.setText("Telefone");

        labelEmailFornecedor.setText("Email");

        tituloEnderecoFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloEnderecoFornecedor.setText("ENDEREÇO");

        labelCodigoEndereco.setText("Código");

        codigoEndereco.setEnabled(false);

        labelCepEndereco.setText("Cep");

        labelCidadeEndereco.setText("Cidade");

        labelEstadoEndereco.setText("Estado");

        botaoSalvarCadastroFornecedor.setText("Salvar");
        botaoSalvarCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarCadastroFornecedorActionPerformed(evt);
            }
        });

        botaoCancelarCadastroFornecedor.setText("Cancelar");

        javax.swing.GroupLayout painelCadastroFornecedorLayout = new javax.swing.GroupLayout(painelCadastroFornecedor);
        painelCadastroFornecedor.setLayout(painelCadastroFornecedorLayout);
        painelCadastroFornecedorLayout.setHorizontalGroup(
            painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroFornecedorLayout.createSequentialGroup()
                        .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloDadosFornecedor)
                            .addComponent(tituloEnderecoFornecedor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelCadastroFornecedorLayout.createSequentialGroup()
                        .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigoFornecedor)
                            .addComponent(labelNomeFornecedor)
                            .addComponent(labelTelefoneFornecedor)
                            .addComponent(labelEmailFornecedor)
                            .addComponent(labelCodigoEndereco)
                            .addComponent(labelCepEndereco)
                            .addComponent(labelEstadoEndereco)
                            .addComponent(labelCidadeEndereco))
                        .addGap(19, 19, 19)
                        .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addComponent(emailFornecedor)
                            .addGroup(painelCadastroFornecedorLayout.createSequentialGroup()
                                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estadoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(telefoneFornecedor)
                                        .addComponent(codigoEndereco)
                                        .addComponent(cepEndereco)
                                        .addComponent(codigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroFornecedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCancelarCadastroFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvarCadastroFornecedor)))
                .addContainerGap())
        );
        painelCadastroFornecedorLayout.setVerticalGroup(
            painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDadosFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefoneFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmailFornecedor))
                .addGap(24, 24, 24)
                .addComponent(tituloEnderecoFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCepEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidadeEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoEndereco)
                    .addComponent(estadoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSalvarCadastroFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCancelarCadastroFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TabsPadaria.addTab("Cadastro Fornecedor", painelCadastroFornecedor);

        tituloDadosProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloDadosProduto.setText("DADOS DO PRODUTO");

        labelCodigoProduto.setText("Código");

        codigoProduto.setEnabled(false);

        labelDescricaoProduto.setText("Descrição");

        labelValorProduto.setText("Valor");

        valorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        labelFornecedorProduto.setText("Fornecedor");

        botaoSalvarProduto.setText("Salvar");
        botaoSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarProdutoActionPerformed(evt);
            }
        });

        botaoCancelarCadastroProduto.setText("Cancelar");

        produtoFornecedor.setModel(listaFornecedores);
        produtoFornecedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        produtoFornecedor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                produtoFornecedorValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(produtoFornecedor);

        javax.swing.GroupLayout painelCadastroProdutoLayout = new javax.swing.GroupLayout(painelCadastroProduto);
        painelCadastroProduto.setLayout(painelCadastroProdutoLayout);
        painelCadastroProdutoLayout.setHorizontalGroup(
            painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroProdutoLayout.createSequentialGroup()
                        .addGap(0, 468, Short.MAX_VALUE)
                        .addComponent(botaoCancelarCadastroProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvarProduto)
                        .addGap(6, 6, 6))
                    .addGroup(painelCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloDadosProduto)
                            .addGroup(painelCadastroProdutoLayout.createSequentialGroup()
                                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCodigoProduto)
                                    .addComponent(labelDescricaoProduto)
                                    .addComponent(labelValorProduto))
                                .addGap(21, 21, 21)
                                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(descricaoProduto)
                                    .addComponent(codigoProduto))))
                        .addGap(18, 287, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroProdutoLayout.createSequentialGroup()
                        .addComponent(labelFornecedorProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        painelCadastroProdutoLayout.setVerticalGroup(
            painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDadosProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoProduto)
                    .addComponent(codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricaoProduto)
                    .addComponent(descricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorProduto)
                    .addComponent(valorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFornecedorProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(painelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarProduto)
                    .addComponent(botaoCancelarCadastroProduto))
                .addContainerGap())
        );

        TabsPadaria.addTab("Cadastro Produto", painelCadastroProduto);

        tituloDadosFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloDadosFuncionario.setText("DADOS DO FUNCIONÁRIO");

        labelCodigoFuncionario.setText("Código");

        codigoFuncionario.setEnabled(false);

        labelNomeFuncionario.setText("Nome");

        labelCpfFuncionario.setText("CPF");

        labelCargoFuncionario.setText("Cargo");

        botaoCancelarFuncionario.setText("Cancelar");

        botaoSalvarFuncionario.setText("Salvar");
        botaoSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroFuncionarioLayout = new javax.swing.GroupLayout(painelCadastroFuncionario);
        painelCadastroFuncionario.setLayout(painelCadastroFuncionarioLayout);
        painelCadastroFuncionarioLayout.setHorizontalGroup(
            painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloDadosFuncionario)
                            .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCpfFuncionario)
                                    .addComponent(labelCargoFuncionario))
                                .addGap(25, 25, 25)
                                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                                        .addComponent(cpfFuncionario)
                                        .addGap(354, 354, 354))))
                            .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(labelCodigoFuncionario)
                                .addGap(18, 18, 18)
                                .addComponent(codigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroFuncionarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoCancelarFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSalvarFuncionario))
                            .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(labelNomeFuncionario)
                                .addGap(24, 24, 24)
                                .addComponent(nomeFuncionario)))
                        .addContainerGap())))
        );
        painelCadastroFuncionarioLayout.setVerticalGroup(
            painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDadosFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoFuncionario)
                    .addComponent(codigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpfFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFuncionario)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCargoFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(painelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarFuncionario)
                    .addComponent(botaoSalvarFuncionario))
                .addContainerGap())
        );

        TabsPadaria.addTab("Cadastro Funcionário", painelCadastroFuncionario);

        tituloFormaPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloFormaPagamento.setText("FORMA DE PAGAMENTO");

        labelCodigoFormaPagamento.setText("Código");

        codigoFormaPagamento.setEnabled(false);

        labelDescricaoFormaPagamento.setText("Descrição");

        botaoSalvarFormaPagamento.setText("Salvar");
        botaoSalvarFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarFormaPagamentoActionPerformed(evt);
            }
        });

        botaoCancelarFormaPagamento.setText("Cancelar");

        javax.swing.GroupLayout painelCadastroFormaPagamentoLayout = new javax.swing.GroupLayout(painelCadastroFormaPagamento);
        painelCadastroFormaPagamento.setLayout(painelCadastroFormaPagamentoLayout);
        painelCadastroFormaPagamentoLayout.setHorizontalGroup(
            painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroFormaPagamentoLayout.createSequentialGroup()
                        .addGap(0, 468, Short.MAX_VALUE)
                        .addComponent(botaoCancelarFormaPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvarFormaPagamento))
                    .addGroup(painelCadastroFormaPagamentoLayout.createSequentialGroup()
                        .addComponent(tituloFormaPagamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelCadastroFormaPagamentoLayout.createSequentialGroup()
                        .addGroup(painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescricaoFormaPagamento)
                            .addComponent(labelCodigoFormaPagamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoFormaPagamento)
                            .addGroup(painelCadastroFormaPagamentoLayout.createSequentialGroup()
                                .addComponent(codigoFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        painelCadastroFormaPagamentoLayout.setVerticalGroup(
            painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoFormaPagamento)
                    .addComponent(codigoFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricaoFormaPagamento)
                    .addComponent(descricaoFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(painelCadastroFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarFormaPagamento)
                    .addComponent(botaoCancelarFormaPagamento))
                .addContainerGap())
        );

        TabsPadaria.addTab("Cadastro Forma de Pagamento", painelCadastroFormaPagamento);

        menuComanda.setText("Comanda");

        menuNovaComanda.setText("Nova Comanda");
        menuNovaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaComandaActionPerformed(evt);
            }
        });
        menuComanda.add(menuNovaComanda);

        jMenuBar1.add(menuComanda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabsPadaria)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabsPadaria)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarCadastroFornecedorActionPerformed
        Endereco endereco = new Endereco();
        endereco.setCep(this.cepEndereco.getText());
        endereco.setCidade(this.cidadeEndereco.getText());
        endereco.setEstado(this.estadoEndereco.getText());
        
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setNome(this.nomeFornecedor.getText());
        fornecedor.setTelefone(this.telefoneFornecedor.getText());
        fornecedor.setEmail(this.emailFornecedor.getText());
        fornecedor.setEndereco(endereco);
        
        new CadastroFornecedor().cadastrar(endereco, fornecedor);
    }//GEN-LAST:event_botaoSalvarCadastroFornecedorActionPerformed

    private void botaoSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarProdutoActionPerformed
        Produto produto = new Produto();
        
        String valorString = this.valorProduto.getText().replace(",", ".");
        double valorDouble = Double.parseDouble(valorString);
        
        produto.setDescricao(this.descricaoProduto.getText());
        produto.setDisponivel(true);
        produto.setValor(valorDouble);
        produto.setFornecedor(produtoFornecedorSelecionado);
        
        new CadastroProduto().cadastrar(produto);
    }//GEN-LAST:event_botaoSalvarProdutoActionPerformed

    private void botaoSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarFuncionarioActionPerformed
        Funcionario funcionario = new Funcionario();
        funcionario.setCargo(this.cargoFuncionario.getText());
        funcionario.setNome(this.nomeFuncionario.getText());
        funcionario.setCpf(this.cpfFuncionario.getText());
        
        new CadastroFuncionario().cadastrar(funcionario);
    }//GEN-LAST:event_botaoSalvarFuncionarioActionPerformed

    private void botaoSalvarFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarFormaPagamentoActionPerformed
        FormaPagamento formapagamento = new FormaPagamento();
        formapagamento.setDescricao(this.descricaoFormaPagamento.getText());
        
        new CadastroFormaPagamento().cadastrar(formapagamento);
    }//GEN-LAST:event_botaoSalvarFormaPagamentoActionPerformed

    private void TabsPadariaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabsPadariaStateChanged
        listarFornecedores();
    }//GEN-LAST:event_TabsPadariaStateChanged

    private void menuNovaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaComandaActionPerformed
        new ComandaCliente().setVisible(true);
    }//GEN-LAST:event_menuNovaComandaActionPerformed

    private void produtoFornecedorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_produtoFornecedorValueChanged
        produtoFornecedorSelecionado = produtoFornecedor.getSelectedValue();
    }//GEN-LAST:event_produtoFornecedorValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Padaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Padaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Padaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Padaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Padaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabsPadaria;
    private javax.swing.JButton botaoCancelarCadastroFornecedor;
    private javax.swing.JButton botaoCancelarCadastroProduto;
    private javax.swing.JButton botaoCancelarFormaPagamento;
    private javax.swing.JButton botaoCancelarFuncionario;
    private javax.swing.JButton botaoSalvarCadastroFornecedor;
    private javax.swing.JButton botaoSalvarFormaPagamento;
    private javax.swing.JButton botaoSalvarFuncionario;
    private javax.swing.JButton botaoSalvarProduto;
    private javax.swing.JTextField cargoFuncionario;
    private javax.swing.JTextField cepEndereco;
    private javax.swing.JTextField cidadeEndereco;
    private javax.swing.JTextField codigoEndereco;
    private javax.swing.JTextField codigoFormaPagamento;
    private javax.swing.JTextField codigoFornecedor;
    private javax.swing.JTextField codigoFuncionario;
    private javax.swing.JTextField codigoProduto;
    private javax.swing.JTextField cpfFuncionario;
    private javax.swing.JTextField descricaoFormaPagamento;
    private javax.swing.JTextField descricaoProduto;
    private javax.swing.JTextField emailFornecedor;
    private javax.swing.JTextField estadoEndereco;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCargoFuncionario;
    private javax.swing.JLabel labelCepEndereco;
    private javax.swing.JLabel labelCidadeEndereco;
    private javax.swing.JLabel labelCodigoEndereco;
    private javax.swing.JLabel labelCodigoFormaPagamento;
    private javax.swing.JLabel labelCodigoFornecedor;
    private javax.swing.JLabel labelCodigoFuncionario;
    private javax.swing.JLabel labelCodigoProduto;
    private javax.swing.JLabel labelCpfFuncionario;
    private javax.swing.JLabel labelDescricaoFormaPagamento;
    private javax.swing.JLabel labelDescricaoProduto;
    private javax.swing.JLabel labelEmailFornecedor;
    private javax.swing.JLabel labelEstadoEndereco;
    private javax.swing.JLabel labelFornecedorProduto;
    private javax.swing.JLabel labelNomeFornecedor;
    private javax.swing.JLabel labelNomeFuncionario;
    private javax.swing.JLabel labelTelefoneFornecedor;
    private javax.swing.JLabel labelValorProduto;
    private javax.swing.JMenu menuComanda;
    private javax.swing.JMenuItem menuNovaComanda;
    private javax.swing.JTextField nomeFornecedor;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JPanel painelCadastroFormaPagamento;
    private javax.swing.JPanel painelCadastroFornecedor;
    private javax.swing.JPanel painelCadastroFuncionario;
    private javax.swing.JPanel painelCadastroProduto;
    private javax.swing.JList<Fornecedor> produtoFornecedor;
    private javax.swing.JTextField telefoneFornecedor;
    private javax.swing.JLabel tituloDadosFornecedor;
    private javax.swing.JLabel tituloDadosFuncionario;
    private javax.swing.JLabel tituloDadosProduto;
    private javax.swing.JLabel tituloEnderecoFornecedor;
    private javax.swing.JLabel tituloFormaPagamento;
    private javax.swing.JFormattedTextField valorProduto;
    // End of variables declaration//GEN-END:variables
}
